import type { Monaco } from "@monaco-editor/react";

let registered = false;

/** Monaco language id used by the geometry C# editor (avoids clobbering built-in csharp). */
export const CSHARP_GEOM_LANGUAGE_ID = "csharp-geom";

/**
 * Richer C# highlighting for the geometry host:
 * built-in C# keywords + Terraria-like API types/members.
 */
export function registerCsharpLanguage(monaco: Monaco): void {
	if (registered) return;
	registered = true;

	monaco.languages.register({ id: CSHARP_GEOM_LANGUAGE_ID });

	monaco.languages.setLanguageConfiguration(CSHARP_GEOM_LANGUAGE_ID, {
		comments: {
			lineComment: "//",
			blockComment: ["/*", "*/"],
		},
		brackets: [
			["{", "}"],
			["[", "]"],
			["(", ")"],
			["<", ">"],
		],
		autoClosingPairs: [
			{ open: "{", close: "}" },
			{ open: "[", close: "]" },
			{ open: "(", close: ")" },
			{ open: "'", close: "'", notIn: ["string", "comment"] },
			{ open: "\"", close: "\"", notIn: ["string", "comment"] },
			{ open: "/*", close: "*/", notIn: ["string"] },
		],
		surroundingPairs: [
			{ open: "{", close: "}" },
			{ open: "[", close: "]" },
			{ open: "(", close: ")" },
			{ open: "'", close: "'" },
			{ open: "\"", close: "\"" },
			{ open: "<", close: ">" },
		],
	});

	monaco.languages.setMonarchTokensProvider(CSHARP_GEOM_LANGUAGE_ID, {
		defaultToken: "",
		tokenPostfix: ".cs",
		keywords: [
			"abstract",
			"as",
			"base",
			"break",
			"case",
			"catch",
			"checked",
			"class",
			"const",
			"continue",
			"default",
			"delegate",
			"do",
			"else",
			"enum",
			"event",
			"explicit",
			"extern",
			"false",
			"finally",
			"fixed",
			"for",
			"foreach",
			"goto",
			"if",
			"implicit",
			"in",
			"interface",
			"internal",
			"is",
			"lock",
			"namespace",
			"new",
			"null",
			"operator",
			"out",
			"override",
			"params",
			"private",
			"protected",
			"public",
			"readonly",
			"ref",
			"return",
			"sealed",
			"sizeof",
			"stackalloc",
			"static",
			"struct",
			"switch",
			"this",
			"throw",
			"true",
			"try",
			"typeof",
			"unchecked",
			"unsafe",
			"using",
			"virtual",
			"volatile",
			"while",
			"add",
			"alias",
			"ascending",
			"async",
			"await",
			"by",
			"descending",
			"dynamic",
			"equals",
			"from",
			"get",
			"global",
			"group",
			"into",
			"join",
			"let",
			"nameof",
			"on",
			"orderby",
			"partial",
			"remove",
			"select",
			"set",
			"value",
			"var",
			"when",
			"where",
			"yield",
			"record",
			"init",
			"with",
			"nint",
			"nuint",
			"file",
			"required",
			"scoped",
		],
		typeKeywords: [
			"bool",
			"byte",
			"char",
			"decimal",
			"double",
			"float",
			"int",
			"long",
			"object",
			"sbyte",
			"short",
			"string",
			"uint",
			"ulong",
			"ushort",
			"void",
			// Geometry host / XNA-like API
			"Vector2",
			"Vector3",
			"Vector4",
			"Color",
			"Vertex2D",
			"VertexList",
			"List",
			"MathHelper",
			"MathF",
			"PrimitiveType",
			"Texture2D",
			"GraphicsDevice",
			"Main",
			"Commons",
			"ModAsset",
			"Assets",
			"Matrix",
			"Rectangle",
		],
		builtins: [
			"Add",
			"ToArray",
			"Count",
			"RotatedBy",
			"Lerp",
			"White",
			"Black",
			"Transparent",
			"DrawUserPrimitives",
			"Textures",
			"Value",
			"Get",
			"Sin",
			"Cos",
			"Abs",
			"Sqrt",
			"Min",
			"Max",
			"Floor",
			"Ceiling",
			"TwoPi",
			"Pi",
			"PiOver2",
			"TriangleStrip",
			"TriangleList",
			"Draw",
			"DrawRing",
			"iTime",
			"iResolution",
			"iMouse",
		],
		operators: [
			"=",
			">",
			"<",
			"!",
			"~",
			"?",
			":",
			"==",
			"<=",
			">=",
			"!=",
			"&&",
			"||",
			"++",
			"--",
			"+",
			"-",
			"*",
			"/",
			"&",
			"|",
			"^",
			"%",
			"<<",
			">>",
			"+=",
			"-=",
			"*=",
			"/=",
			"=>",
			"??",
			"?.",
			"??=",
		],
		symbols: /[=><!~?:&|+\-*/^%]+/,
		escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
		tokenizer: {
			root: [
				// identifiers & keywords
				[
					/[a-zA-Z_]\w*/,
					{
						cases: {
							"@keywords": "keyword",
							"@typeKeywords": "type",
							"@builtins": "predefined",
							"@default": "identifier",
						},
					},
				],
				{ include: "@whitespace" },
				[/[{}()[\]]/, "@brackets"],
				[/[<>](?!@symbols)/, "@brackets"],
				[
					/@symbols/,
					{
						cases: {
							"@operators": "operator",
							"@default": "",
						},
					},
				],
				// numbers with C# suffixes
				[/\d*\.\d+([eE][-+]?\d+)?[fFdDmM]?/, "number.float"],
				[/\d+[eE][-+]?\d+[fFdDmM]?/, "number.float"],
				[/\d+[fFdDmM]/, "number.float"],
				[/0[xX][0-9a-fA-F_]+[uUlL]*/, "number.hex"],
				[/\d+[uUlL]*/, "number"],
				[/[;,.]/, "delimiter"],
				[/"([^"\\]|\\.)*$/, "string.invalid"],
				[/"/, "string", "@string"],
				[/'[^\\']'/, "string"],
				[/(')(@escapes)(')/, ["string", "string.escape", "string"]],
				[/'/, "string.invalid"],
			],
			whitespace: [
				[/[ \t\r\n]+/, "white"],
				[/\/\*/, "comment", "@comment"],
				[/\/\/.*$/, "comment"],
			],
			comment: [
				[/[^/*]+/, "comment"],
				[/\*\//, "comment", "@pop"],
				[/[/*]/, "comment"],
			],
			string: [
				[/[^\\"]+/, "string"],
				[/@escapes/, "string.escape"],
				[/\\./, "string.escape.invalid"],
				[/"/, "string", "@pop"],
			],
		},
	});
}
